# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58c32780373c89e0791ed00bae6eec2a99db93955627a99eb40a5c7e48ff8d2ed8c5965e18e9895b5d49433f8a33a6ac591dcb48bc37a43065acb48ce81d4746

test:
  secret_key_base: 4db983e727ec514b208b891439aabcd027c0defb0098a1696a602d467bc2c50d9183efd3fff84c37d19595edf8d151d11c8af4a500719ee8be58be4e54fe6c38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
